apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-java
  labels:
    app: hello-java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-java
  template:
    metadata:
      labels:
        app: hello-java
    spec:
      containers:
        - name: app
          image: ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/hello-java:1.0
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: MESSAGE
              value: "Hello from EKS!"
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: hello-java
  labels:
    app: hello-java
spec:
  selector:
    app: hello-java
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer
